class AppStrings {
  AppStrings._();

  static const String appName = 'MyWallet';
  static String appVersion = '';
  static const String emptyString = '';
  static const String login = 'Login';
  static const String signup = 'Signup';
  static const String submit = 'Submit';
  static const String rememberMe = 'Remember Me';
  static const String forgotPassword = 'Forgot Password';
  static const String continueString = 'Continue';
  static const String dontHaveAccount = "Don't have an account";
  static const String alreadyHaveAccount = 'Already have an account';
  static const String all = 'All';
  static const String transfer = 'Transfer';
  static const String receive = 'Receive';
  static const String amount = 'Amount';
  static const String name = 'Name';
  static const String availableBalance = 'Available Balance';
  static const String transaction = 'Transaction';
  static const String transactionType = 'Transaction Type';
  static const String date = 'Date';
  static const String totalAmount = 'Total Amount';
  static const String email = 'Email';
  static const String password = 'Password';
  static const String dashboard = 'Dashboard';
  static const String okay = 'Ok';
  static const String no = 'No';
  static const String yes = 'Yes';
  static const String cancel = 'Cancel';
  static const String close = 'Close';
  static const String logout = 'Logout';
  static const String exit = 'Exit';
  static const String error = 'Error';
  static const String failed = 'Failed';
  static const String addUser = 'Add User';
  static const String addTransaction = 'Add Transaction';
  static const String emptyAmount = 'Please enter amount';
  static const String emptyDate = 'Please select date of transaction';
  static const String noTransactionFound = 'No transaction found';
  static const String type = 'Type';
  static const String profile = 'Profile';
  static const String phone = 'Phone';
  static const String address = 'Address';
  static const String update = 'Update';
  static const String userId = 'User Id';
  static const String selectImage = 'Select Image';
  static const String gallery = 'Gallery';
  static const String camera = 'Camera';
  static const String userProfile = 'User Profile';
  static const String biometricAuthFailedMessage = 'My Wallet protects your data to avoid unauthorized access.';
  static const String bioAuthFailedTooManyAttemptMessage = 'Biometric authentication failed because the API is locked out due to too many attempts. This occurs after 5 failed attempts';
  static const String biometricAuthFailed = 'Biometric Authentication Failed';
  static const String biometricMessage = 'To continue, you must complete the biometrics';
  static const String reAuthenticate = 'Re-Authenticate';
  static const String profileUpdatedMsg = 'Profile updated successfully';
  static const String deleteUser = 'Delete User';
  static const String language = 'Language';
  static const String english = 'English';
  static const String hindi = 'Hindi';
  static const String settings = 'Settings';
  static const String viewProfile = 'View Profile';
  static const String success = 'Success';
  static const String back = 'Back';

  ///Warning and Error Messages
  static const String logoutMessage = 'Are you sure you want to logout?';
  static const String exitMessage = 'Are you sure you want to exit?';
  static const String somethingWentWrong = 'Something went wrong';
  static const String noInternetConnection = 'No Internet Connection';
  static const String noInternetConnectionMessage = 'Please check your internet connection';
  static const String emptyEmail = 'Please provide email';
  static const String emptyName = 'Please provide name';
  static const String invalidEmail = 'Please provide valid email';
  static const String emptyPassword = 'Please provide password';
  static const String invalidPassword = 'Weak password, Length of password should be atleast 8 character';
  static const String dialogShowingMessage = 'Loading dialog already showing';
  static const String dialogNotShowingMessage = 'Loading dialog is not showing'; 
  static const String noUserFound = 'No user found';
  static const String emailAlreadyExist = 'Email already exist';
  static const String deleteUserMsg = 'Are you sure you want to delete';
  static const String forgotPasswordMsg = "Enter the email address associated with your account and we'll send you a link to reset your password";
  static const String invalidPhone = "Please provide valid phone number";
  static const String imageSizeMsg = "Image size should not be more than 2MB";
  static const String userDeletedMsg = "User has been deleted successfully";
  static const String continueWithGoogle = "Continue with Google";
  static const String termAndPolilcy = "  Terms & Privacy Policy";

  ////Preferences Key Constant
  static const String prefEmail = 'PREF_EMAIL';
  static const String prefFullName = 'PREF_FULL_NAME';
  static const String prefPassword = 'PREF_PASSWORD';
  static const String prefRememberMe = 'PREF_REMEMBER_ME';
  static const String prefUserId = 'PREF_USER_ID';
  static const String prefBiometric = 'PREF_BIOMETRIC';
  static const String prefEnableBiometric = 'PREF_ENABLE_BIOMETRIC';
  static const String prefBiometricAuthentication = 'PREF_BIOMETRIC_AUTHENTICATION';
  static const String prefProfileImg = 'PREF_PROFILE_IMG';
  static const String prefLanguage = 'PREF_LANGUAGE';
  static const String prefTheme = 'PREF_THEME';

  ///sample image
  static const String sampleImg = "https://images.unsplash.com/photo-1613891188927-14c2774fb8d7?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTh8fGh1bWluZyUyMGJpcmR8ZW58MHx8MHx8fDA%3D";
  static const String privacyPolicyUrl = 'https://alihasan-dev.github.io/my_wallet/privacy_policy.html';
  static const String webUrl = 'https://my-wallet-99fdf.web.app/';
}